<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_products' => 'Products',
		'tt_products.price' => 'Price:',
		'tt_products.price2' => 'Price (2):',
		'tt_products.itemnumber' => 'Item number:',
		'tt_products.inStock' => 'In Stock (pcs):',
		'tt_products_cat' => 'Product category',
	),
	'dk' => Array (
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Emne nummer:',
		'tt_products.inStock' => 'Pе lager (stk):',
		'tt_products_cat' => 'Produkt kategori',
	),
	'de' => Array (
		'tt_products' => 'Produkte',
		'tt_products.price' => 'Preis:',
		'tt_products.price2' => 'Preis (2):',
		'tt_products.itemnumber' => 'Artikel Nr.:',
		'tt_products.inStock' => 'Am Lager (St.):',
		'tt_products_cat' => 'Produkt Kategorie',
	),
	'no' => Array (
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Emne nummer:',
		'tt_products.inStock' => 'Pе lager (stk.):',
		'tt_products_cat' => 'Produkt kategori',
	),
	'it' => Array (
		'tt_products' => 'Prodotti',
		'tt_products.price' => 'Prezzo:',
		'tt_products.price2' => 'Prezzo(2):',
		'tt_products.itemnumber' => 'Numero item:',
		'tt_products.inStock' => 'In giacenza (p.zi):',
		'tt_products_cat' => 'Categoria prodotto',
	),
	'fr' => Array (
		'tt_products' => 'Produits',
		'tt_products.price' => 'Prix:',
		'tt_products.price2' => 'Prix (2):',
		'tt_products.itemnumber' => 'No article:',
		'tt_products.inStock' => 'En stocks (pcs):',
		'tt_products_cat' => 'Catйgorie de produit',
	),
	'es' => Array (
		'tt_products' => 'Productos',
		'tt_products.price' => 'Precio:',
		'tt_products.price2' => 'Precio (2):',
		'tt_products.itemnumber' => 'N° de parte:',
		'tt_products.inStock' => 'En existencia (pz.):',
		'tt_products_cat' => 'Categorнa de producto',
	),
	'nl' => Array (
		'tt_products' => 'Producten',
		'tt_products.price' => 'Prijs:',
		'tt_products.price2' => 'Prijs (2):',
		'tt_products.itemnumber' => 'Item nummer:',
		'tt_products.inStock' => 'Per Stuk (stks):',
		'tt_products_cat' => 'Product categorie',
	),
	'cz' => Array (
		'tt_products' => 'Produkty',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => 'Инslo poloћky:',
		'tt_products.inStock' => 'Na skladм (ks):',
		'tt_products_cat' => 'Kategorie produktu',
	),
	'pl' => Array (
		'tt_products' => 'Produkty',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => 'Ilo¶ж:',
		'tt_products.inStock' => 'Sztuk:',
		'tt_products_cat' => 'Kategoria produktu',
	),
	'si' => Array (
		'tt_products' => 'Izdelki',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => 'Љt. izdelka:',
		'tt_products.inStock' => 'Na zalogi (kom):',
	),
	'fi' => Array (
		'tt_products' => 'Tuotteet:',
		'tt_products.price' => 'Hinta:',
		'tt_products.price2' => 'Hinta (2):',
		'tt_products.itemnumber' => 'Tuote numero:',
		'tt_products.inStock' => 'Varastossa (kpl)',
		'tt_products_cat' => 'Tuoteluokka',
	),
	'tr' => Array (
		'tt_products' => 'Ьrьnler',
		'tt_products.price' => 'Fiyat:',
		'tt_products.price2' => 'Fiyat (2):',
		'tt_products.itemnumber' => 'Nesne numarasэ:',
		'tt_products.inStock' => 'Stoktaki (prз):',
		'tt_products_cat' => 'Ьrьn kategorisi',
	),
	'se' => Array (
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Produkt nr:',
		'tt_products.inStock' => 'I lager (st):',
		'tt_products_cat' => 'Produktkategori',
	),
	'pt' => Array (
		'tt_products' => 'Produtos',
		'tt_products.price' => 'Preзo:',
		'tt_products.price2' => 'Preзo (2):',
		'tt_products.itemnumber' => 'Nъmero do item:',
		'tt_products.inStock' => 'Em armazйm (pзs):',
		'tt_products_cat' => 'Categoria do produto',
	),
	'ru' => Array (
		'tt_products' => 'Продукты',
		'tt_products.price' => 'Цена:',
		'tt_products.price2' => 'Цена (2):',
		'tt_products.itemnumber' => 'Номенклатура:',
		'tt_products.inStock' => 'На складе (штук):',
		'tt_products_cat' => 'Категория продуктов',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
);
?>