<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_content.tt_products_code.I.0' => 'LIST',
		'tt_content.tt_products_code.I.1' => 'LISTOFFERS',
		'tt_content.tt_products_code.I.2' => 'LISTHIGHLIGHTS',
		'tt_content.tt_products_code.I.3' => 'LISTNEWITEMS',
		'tt_content.tt_products_code.I.4' => 'SINGLE',
		'tt_content.tt_products_code.I.5' => 'SEARCH',
		'tt_content.tt_products_code.I.6' => 'MEMO',
		'tt_content.tt_products_code.I.7' => 'BASKET',
		'tt_content.tt_products_code.I.8' => 'INFO',
		'tt_content.tt_products_code.I.9' => 'PAYMENT',
		'tt_content.tt_products_code.I.10' => 'FINALIZE',
		'tt_content.tt_products_code.I.11' => 'OVERVIEW',
		'tt_content.tt_products_code.I.12' => 'TRACKING',
		'tt_content.tt_products_code.I.13' => 'BILL',
		'tt_content.tt_products_code.I.14' => 'DELIVERY',
		'tt_content.tt_products_code.I.15' => 'HELP',
		'tt_content.tt_products_code.I.16' => 'CURRENCY',
/* Added Els: I.17 ORDERS */
		'tt_content.tt_products_code.I.17' => 'ORDERS',
		'tt_content.tt_products_code' => 'Code',
		'tt_products' => 'Products',
		'tt_products.price' => 'Price:',
		'tt_products.price2' => 'Price (2):',
		'tt_products.unit' => 'Unit of measure',
		'tt_products.unit_factor' => 'Unit factor',
		'tt_products.itemnumber' => 'Item number:',
		'tt_products.inStock' => 'In Stock (pcs):',
		'tt_products.datasheet' => 'Datasheet',
		'tt_products.tax' => 'Tax:',
		'tt_products.weight' => 'Weight (kg):',
		'tt_products.bulkily' => 'Bulkily:',
		'tt_products.offer' => 'Offer:',
		'tt_products.highlight' => 'Highlight:',
		'tt_products.directcost' => 'Direct Cost:',
		'tt_products.color' => 'Color (Variant 1):',
		'tt_products.size' => 'Size (Variant 2):',
		'tt_products.accessory' => 'Price Accessory (Variant 3):',
		'tt_products.accessory2' => 'Price 2 Accessory:',
		'tt_products.special_preparation' => 'Special Preparation:',
		'tt_products.gradings' => 'Gradings:',
		'tt_products.subtitle' => 'Subtitle:',
		'tt_products_language' => 'Products (alternative language)',
		'tt_products_language.prd_uid' => 'Product record',
		'tt_products_language.sys_language_uid' => 'Language',
		'tt_products_language.datasheet' => 'Datasheet',
		'tt_products_cat' => 'Product category',
		'tt_products_cat.parent_cat' => 'Parent category',
		'tt_products_cat_language' => 'Product category (alternative language)',
		'tt_products_cat_language.sys_language_uid' => 'Language',
		'tt_products_cat_language.cat_uid' => 'Product category record',
		"tt_content.list_type_pi1" => "Products",
		'fe_users.tt_products_memoItems' => 'Memo Items',
		'fe_users.tt_products_discount' => 'Discount',
/* mkl:		'tt_content.pi_flexform.display_mode' => 'Display mode',
		'tt_content.pi_flexform.display_mode.1' => 'Products: list',
		'tt_content.pi_flexform.display_mode.2' => 'Products: single',
		'tt_content.pi_flexform.display_mode.3' => 'Products: search',
		'tt_content.pi_flexform.display_mode.4' => 'Basket: content',
		'tt_content.pi_flexform.display_mode.5' => 'Basket: payment',
		'tt_content.pi_flexform.display_mode.6' => 'Basket: finalize',
		'tt_content.pi_flexform.display_mode.7' => 'Basket: info',
		'tt_content.pi_flexform.display_mode.8' => 'Orders: tracking',
		'tt_content.pi_flexform.display_mode.9' => 'Currency: selector', */
	),
	'dk' => Array (
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Emne nummer:',
		'tt_products.inStock' => 'Pе lager (stk):',
		'tt_products_cat' => 'Produkt kategori',
	),
	'de' => Array (
		'tt_products' => 'Produkte',
		'tt_products.price' => 'Preis:',
		'tt_products.price2' => 'Preis (2):',
		'tt_products.itemnumber' => 'Artikel Nr.:',
		'tt_products.inStock' => 'Am Lager (St.):',
		'tt_products.tax' => 'MwSt:',
		'tt_products.weight' => 'Gewicht (kg):',
		'tt_products.bulkily' => 'Sperrig:',
		'tt_products.offer' => 'Angebot:',
		'tt_products.highlight' => 'Neuheit:',
		'tt_products.directcost' => 'Einkaufspreis:',
		'tt_products.color' => 'Farbe (Variante 1):',
		'tt_products.size' => 'GrцЯe (Variante 2):',
		'tt_products.accessory' => 'Aufpreis Zubehцr (Variante 3):',
		'tt_products.accessory2' => 'Aufpreis 2 Zubehцr:',
		'tt_products.special_preparation' => 'Spezialanfertigung:',
		'tt_products.gradings' => 'Staffelungen:',
		'tt_products.subtitle' => 'Untertitel:',
		'tt_products_cat' => 'Produkt Kategorie',
		'fe_users.tt_products_memoItems' => 'Merkliste',
		'fe_users.tt_products_discount' => 'Rabatt',
	),
	'no' => Array (
		'tt_content.tt_products_code' => 'Kode',
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Varenr:',
		'tt_products.inStock' => 'Pе lager (stk.):',
		'tt_products.tax' => 'Mva (%):',
		'tt_products.weight' => 'Vekt (kg):',
		'tt_products.bulkily' => 'Stor:',
		'tt_products.offer' => 'Tilbud:',
		'tt_products.highlight' => 'Utvalgt:',
		'tt_products.directcost' => 'Kostpris:',
		'tt_products.color' => 'Farge:',
		'tt_products.size' => 'Stшrrelse:',
		'tt_products.special_preparation' => 'Preparering:',
		'tt_products.subtitle' => 'Undertittel',
		'tt_products_cat' => 'Produktkategori',
		'fe_users.tt_products_memoItems' => 'Notater',
		'fe_users.tt_products_discount' => 'Rabatt',
	),
	'it' => Array (
		'tt_products' => 'Prodotti',
		'tt_products.price' => 'Prezzo:',
		'tt_products.price2' => 'Prezzo(2):',
		'tt_products.itemnumber' => 'Numero item:',
		'tt_products.inStock' => 'In giacenza (p.zi):',
		'tt_products_cat' => 'Categoria prodotto',
	),
	'fr' => Array (
		'tt_products' => 'Produits',
		'tt_products.price' => 'Prix:',
		'tt_products.price2' => 'Prix (2):',
		'tt_products.itemnumber' => 'No article:',
		'tt_products.inStock' => 'En stocks (pcs):',
		'tt_products.tax' => 'T.V.A.:',
		'tt_products.weight' => 'Poids (kg):',
		'tt_products.bulkily' => 'Volumineux:',
		'tt_products.offer' => 'Offre:',
		'tt_products.highlight' => 'Nouveautй:',
		'tt_products.directcost' => 'Prix d\'achat:',
		'tt_products.color' => 'Couleur (Variante 1):',
		'tt_products.size' => 'Grandeur (Variante 2):',
		'tt_products.accessory' => 'Prix accessoire (Variante 3):',
		'tt_products.accessory2' => 'Prix 2 accessoire:',
		'tt_products.special_preparation' => 'Modиle Spйcial:',
		'tt_products.gradings' => 'Йchelonnement:',
		'tt_products.subtitle' => 'Sous-titre:',
		'tt_products_cat' => 'Catйgorie de produit',
		'fe_users.tt_products_memoItems' => 'Liste mnйmotechnique',
		'fe_users.tt_products_discount' => 'Rйduction',
	),
	'es' => Array (
		'tt_products' => 'Productos',
		'tt_products.price' => 'Precio:',
		'tt_products.price2' => 'Precio (2):',
		'tt_products.itemnumber' => 'N° de parte:',
		'tt_products.inStock' => 'En existencia (pz.):',
		'tt_products_cat' => 'Categorнa de producto',
	),
	'nl' => Array (
		'tt_products' => 'Producten',
		'tt_products.price' => 'Prijs:',
		'tt_products.price2' => 'Prijs (2):',
		'tt_products.itemnumber' => 'Item nummer:',
		'tt_products.inStock' => 'Per Stuk (stks):',
		'tt_products_cat' => 'Product categorie',
	),
	'cz' => Array (
		'tt_products' => 'Produkty',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => 'Инslo poloћky:',
		'tt_products.inStock' => 'Na skladм (ks):',
		'tt_products_cat' => 'Kategorie produktu',
	),
	'pl' => Array (
		'tt_products' => 'Produkty',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.unit' => 'Jednostka miary',
		'tt_products.unit_factor' => 'Mnoїnik',
		'tt_products.itemnumber' => 'Kod:',
		'tt_products.inStock' => 'Dostкpne:',
		'tt_products.datasheet' => 'Karta katalogowa',
		'tt_products_language' => 'Produkty (jкzyk alternatywny)',
		'tt_products_language.prd_uid' => 'Rekord produktu',
		'tt_products_language.sys_language_uid' => 'Jкzyk',
		'tt_products_language.datasheet' => 'Karta katalogowa',
		'tt_products_cat' => 'Kategoria produktu',
		'tt_products_cat.parent_cat' => 'Kategoria nadrzкdna',
		'tt_products_cat_language' => 'Kategoria produktu (jкzyk alternatywny)',
		'tt_products_cat_language.sys_language_uid' => 'Jкzyk',
		'tt_products_cat_language.cat_uid' => 'Rekord kategori produktu',
		"tt_content.list_type_pi1" => "Produkty",
		'tt_content.pi_flexform.display_mode' => 'Tryb wy¶wietlania',
		'tt_content.pi_flexform.display_mode.1' => 'Produkty: lista',
		'tt_content.pi_flexform.display_mode.2' => 'Produkty: pojedynczo',
		'tt_content.pi_flexform.display_mode.3' => 'Produkty: wyszukiwanie',
		'tt_content.pi_flexform.display_mode.4' => 'Koszyk: zawarto¶ж',
		'tt_content.pi_flexform.display_mode.5' => 'Koszyk: pіatno¶ж',
		'tt_content.pi_flexform.display_mode.6' => 'Koszyk: zakoсczenie',
		'tt_content.pi_flexform.display_mode.7' => 'Koszyk: informacja',
		'tt_content.pi_flexform.display_mode.8' => 'Zamуwienia: ¶ledzenie',
		'tt_content.pi_flexform.display_mode.9' => 'Waluta: wybуr',
	),
	'si' => Array (
		'tt_products' => 'Izdelki',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => 'Љt. izdelka:',
		'tt_products.inStock' => 'Na zalogi (kom):',
		'tt_products_cat' => 'Kategorija izdelka',
	),
	'fi' => Array (
		'tt_content.tt_products_code' => 'Kooodi',
		'tt_products' => 'Tuotteet:',
		'tt_products.price' => 'Hinta:',
		'tt_products.price2' => 'Hinta (2):',
		'tt_products.itemnumber' => 'Tuote numero:',
		'tt_products.inStock' => 'Varastossa (kpl)',
		'tt_products.tax' => 'ALV:',
		'tt_products.weight' => 'Paino (kg):',
		'tt_products.bulkily' => 'Mддrд:',
		'tt_products.offer' => 'Tarjous:',
		'tt_products.highlight' => 'Suositus:',
		'tt_products.directcost' => 'Kustannukset:',
		'tt_products.color' => 'Vдri:',
		'tt_products.size' => 'Koko:',
		'tt_products.special_preparation' => 'Erityiset:',
		'tt_products.gradings' => 'Luokittelut:',
		'tt_products.subtitle' => 'Alanimike:',
		'tt_products_cat' => 'Tuoteluokka',
		'fe_users.tt_products_memoItems' => 'Muistion tiedot',
		'fe_users.tt_products_discount' => 'Alennus',
	),
	'tr' => Array (
		'tt_products' => 'Ьrьnler',
		'tt_products.price' => 'Fiyat:',
		'tt_products.price2' => 'Fiyat (2):',
		'tt_products.itemnumber' => 'Nesne numarasэ:',
		'tt_products.inStock' => 'Stoktaki (prз):',
		'tt_products_cat' => 'Ьrьn kategorisi',
	),
	'se' => Array (
		'tt_content.tt_products_code' => 'Kod',
		'tt_products' => 'Produkter',
		'tt_products.price' => 'Pris:',
		'tt_products.price2' => 'Pris (2):',
		'tt_products.itemnumber' => 'Produkt nr:',
		'tt_products.inStock' => 'I lager (st):',
		'tt_products.tax' => 'Moms:',
		'tt_products.weight' => 'Vikt (Kg):',
		'tt_products.bulkily' => 'Fцrpackning',
		'tt_products.offer' => 'Erbjudande:',
		'tt_products.highlight' => 'Hцjdpunkt:',
		'tt_products.directcost' => 'Direkt kostnad:',
		'tt_products.color' => 'Produktens fдrg:',
		'tt_products.size' => 'Produktens storlek:',
		'tt_products.special_preparation' => 'Speciella egenskaper:',
		'tt_products.gradings' => 'Gradering:',
		'tt_products.subtitle' => 'Underrubrik',
		'tt_products_cat' => 'Produktkategori',
		'fe_users.tt_products_memoItems' => 'Memo Produkter',
		'fe_users.tt_products_discount' => 'Rabatt',
	),
	'pt' => Array (
		'tt_products' => 'Produtos',
		'tt_products.price' => 'Preзo:',
		'tt_products.price2' => 'Preзo (2):',
		'tt_products.itemnumber' => 'Nъmero do item:',
		'tt_products.inStock' => 'Em armazйm (pзs):',
		'tt_products_cat' => 'Categoria do produto',
	),
	'ru' => Array (
		'tt_products' => 'Продукты',
		'tt_products.price' => 'Цена:',
		'tt_products.price2' => 'Цена (2):',
		'tt_products.itemnumber' => 'Номенклатура:',
		'tt_products.inStock' => 'На складе (штук):',
		'tt_products_cat' => 'Категория продуктов',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
		'tt_products' => 'Produkty',
		'tt_products.price' => 'Cena:',
		'tt_products.price2' => 'Cena (2):',
		'tt_products.itemnumber' => 'Инslo poloћky:',
		'tt_products.inStock' => 'V sklade (ks)',
		'tt_products_cat' => 'Kategуria vэrobku',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'tt_content.tt_products_code' => 'Kod',
		'tt_products' => 'Proizvodi',
		'tt_products.price' => 'Cijena:',
		'tt_products.price2' => 'Cijena (2):',
		'tt_products.itemnumber' => 'Broj:',
		'tt_products.inStock' => 'Na zalihi (kom.)',
		'tt_products.tax' => 'PDV:',
		'tt_products.weight' => 'Teћina (kg):',
		'tt_products.bulkily' => 'Glomazno:',
		'tt_products.offer' => 'Ponuda:',
		'tt_products.highlight' => 'Istaknuto:',
		'tt_products.directcost' => 'Direktna cijena:',
		'tt_products.color' => 'Boja:',
		'tt_products.size' => 'Veliиina:',
		'tt_products.special_preparation' => 'Posebna priprema:',
		'tt_products.gradings' => 'Stupnjevanje:',
		'tt_products.subtitle' => 'Podnaslov:',
		'tt_products_cat' => 'Kategorija proizvoda:',
		'fe_users.tt_products_memoItems' => 'Memo',
		'fe_users.tt_products_discount' => 'Popust',
	),
	'hu' => Array (
		'tt_products' => 'Termйkek',
		'tt_products.price' => 'Бr:',
		'tt_products.price2' => 'Бr (2):',
		'tt_products.itemnumber' => 'Tйtelszбm:',
		'tt_products.inStock' => 'Raktбron (db):',
		'tt_products_cat' => 'Termйk kategуria',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
		'tt_products' => 'ІЈ«~',
		'tt_products.price' => '»щїъЎG',
		'tt_products.price2' => '»щїъЎ]ў±Ў^ЎG',
		'tt_products.itemnumber' => 'іf«~Ѕsё№ЎG',
		'tt_products.inStock' => '®w¦sЎ]ҐуЎ^ЎG',
		'tt_products_cat' => 'ІЈ«~Гю§O',
	),
	'eu' => Array (
	),
	'bg' => Array (
		'tt_products' => 'Продукти',
		'tt_products.price' => 'Цена:',
		'tt_products.price2' => 'Цена (2):',
		'tt_products.itemnumber' => 'Номер на артикула:',
		'tt_products.inStock' => 'На склад (броя):',
		'tt_products_cat' => 'Продуктова категория',
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>